### PR TITLE
Upgrading gatsby and packages

### LINKED ISSUE #22: Upgrade Gatsby to latest current version
## Summary

As a developer, I would like this site to use the latest current version of [gatsby.js](https://www.gatsbyjs.com/).

## Describe the possible solution

The current version would need to be upgraded to the current version.
Upgrade all additional libraries and ensure they continue to function as they should.

## Describe alternatives you've considered

N/A

## Additional context

N/A

### PR DESCRIPTION
**Pull request by karpin00x**
Closes #22

### CODE REVIEW

**Comment by mikelax** [comment]
@karpin00x do you want to rebase this PR to resolve the conflict? I just merged your other PR.

**Comment by karpin00x** [comment]
Yes, will do.

**Comment by karpin00x** [comment]
I've resolved the conflict, can you check now please ?

**Comment by mikelax** [comment]
@karpin00x this is now looking good once I upgraded the CI to use node.js v10. 
Can you update the version of `node-sass` to `4.14.1`, this will allow me to update to node.js v14

**Comment by karpin00x** [comment]
Of course, will do.

**Pull request merged**
